name: "Auto Author Assign"

on:
    pull_request_target:
        types: [opened]

jobs:
    assign-author:
        runs-on: ubuntu-latest
        steps:
            - uses: toshimaru/auto-author-assign@eac0d15f4a55d1d1824f2b78fdea42de6cd59fef
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
